### ISSUE TITLE
deb package not available

### ISSUE THREAD

**Issue by RadioactivePlays** [jaxparrow07/Androidx86-Installer-Linux#10]
the DEB package isnt available at latest release?

**Comment by jaxparrow07** [comment]
Yes, I published the latest one as a standalone executable. It allows you to run on other distros as well ( if there are required libs ). <br>

You can run that by simply double clicking ( works in most file managers ) or by executing it via terminal `./<file name>` ( allows you to see logs ).

**Comment by RadioactivePlays** [comment]
Thank you.
