### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by alimsk** [jaxparrow07/Androidx86-Installer-Linux#3]
this error occurs when installing Bliss OS 14 (experimental version) on Ubuntu 20.04 LTS
```
Traceback (most recent call last):
  File "installer.py", line 549, in Extracting
  File "genericpath.py", line 50, in getsize
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/ax86_9248283/ramdisk.img'
[1]    9112 abort (core dumped)  androidx86-installer
```
full output:
```
$ androidx86-installer

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,4 CPUs Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz (506E3),ASM,AES-NI)

Scanning the drive for archives:
1 file, 1538260992 bytes (1467 MiB)

Extracting archive: /home/bro/Downloads/BlissOS-14.3-x86_64-202106261907_k-android12-5.10.46-ax86_m-21.1.3_r-x86_emugapps_cros-hd.iso

WARNINGS:
There are data after the end of archive

--
Path = /home/bro/Downloads/BlissOS-14.3-x86_64-202106261907_k-android12-5.10.46-ax86_m-21.1.3_r-x86_emugapps_cros-hd.iso
Type = Iso
WARNINGS:
There are data after the end of archive
Physical Size = 1537585152
Tail Size = 675840
Created = 2021-06-27 08:40:46
Modified = 2021-06-27 08:40:46

Everything is Ok     

Archives with Warnings: 1

Warnings: 1
Folders: 9
Files: 86
Size:       1541576005
Compressed: 1538260992
Traceback (most recent call last):
  File "installer.py", line 549, in Extracting
  File "genericpath.py", line 50, in getsize
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/ax86_9248283/ramdisk.img'
[1]    9112 abort (core dumped)  androidx86-installer
```
just for info, previously I tried to replace the username to my second account username (where the iso file is).
but I didn't notice if there was any text I haven't changed, so I edited my comment, thanks (**just ignore it if you don't understand, this has nothing to do with the error**)

**Comment by jaxparrow07** [comment]
Hey, can you check the file you downloaded is not corrupted or has every required files.

**Comment by jaxparrow07** [comment]
> this error occurs when installing Bliss OS 14 (experimental version) on Ubuntu 20.04 LTS
> 
> ```
> Traceback (most recent call last):
>   File "installer.py", line 549, in Extracting
>   File "genericpath.py", line 50, in getsize
> FileNotFoundError: [Errno 2] No such file or directory: '/tmp/ax86_9248283/ramdisk.img'
> [1]    9112 abort (core dumped)  androidx86-installer
> ```
> 
> full output:
> 
> ```
> $ androidx86-installer
> 
> 7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
> p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,4 CPUs Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz (506E3),ASM,AES-NI)
> 
> Scanning the drive for archives:
> 1 file, 1538260992 bytes (1467 MiB)
> 
> Extracting archive: /home/sky322/Downloads/BlissOS-14.3-x86_64-202106261907_k-android12-5.10.46-ax86_m-21.1.3_r-x86_emugapps_cros-hd.iso
> 
> WARNINGS:
> There are data after the end of archive
> 
> --
> Path = /home/bro/Downloads/BlissOS-14.3-x86_64-202106261907_k-android12-5.10.46-ax86_m-21.1.3_r-x86_emugapps_cros-hd.iso
> Type = Iso
> WARNINGS:
> There are data after the end of archive
> Physical Size = 1537585152
> Tail Size = 675840
> Created = 2021-06-27 08:40:46
> Modified = 2021-06-27 08:40:46
> 
> Everything is Ok     
> 
> Archives with Warnings: 1
> 
> Warnings: 1
> Folders: 9
> Files: 86
> Size:       1541576005
> Compressed: 1538260992
> Traceback (most recent call last):
>   File "installer.py", line 549, in Extracting
>   File "genericpath.py", line 50, in getsize
> FileNotFoundError: [Errno 2] No such file or directory: '/tmp/ax86_9248283/ramdisk.img'
> [1]    9112 abort (core dumped)  androidx86-installer
> ```

It seems like the new bliss os builds doesn't have ramdisk. I will fix this asap. Thanks for reporting.

**Comment by electrikjesus** [comment]
Any Android-x86 10/11 based iso will not have a ramdisk.img, so we can essentially skip the extraction of that when it's not deteced.

**Comment by jaxparrow07** [comment]
This issue has been resolved. `ramdisk.img` has been added to optional files list and the installer will skip if doesn't exist. I will publish next version asap. Thanks for reporting.
