### ISSUE TITLE
How to install from source?

### ISSUE THREAD

**Issue by Peng1029** [jaxparrow07/Androidx86-Installer-Linux#5]
I'm using solus right now and don't have access to apt or dpkg, how would one install from source?

also do you know after I install(I have installed this before on Debian several times) how I could send a file to the android home folder while on linux, and is there anyway to mount the linux partition from android?

**Comment by ilhan-athn7** [comment]
Android os files should be found under
**/home/_somethink_** directory

Android not has home folder unlike GNU/linux distro,
Here is the "Internal Storage" directory of android
/**home/_somethink_/data/media/0**

You can directly access files of your linux partition from " **/gearlock/gearroot** " on android.

**Comment by jaxparrow07** [comment]
> I'm using solus right now and don't have access to apt or dpkg, how would one install from source?

The project is being refactored and will be updated soon.

> also do you know after I install(I have installed this before on Debian several times) how I could send a file to the android home folder while on linux, and is there anyway to mount the linux partition from android?

The above reply answers your question :)
