### ISSUE TITLE
Error on install PrimeOS 2.1.0

### ISSUE THREAD

**Issue by Gzushgshsh** [jaxparrow07/Androidx86-Installer-Linux#8]
OS: Lubuntu 22.04
PrimeOS version: PrimeOS-2.1.0-64-bit-20220223-BETA 
                            (PrimeOS-0.6.1 standard, mainline and classic work normally)

    Command line:
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
libGL error: MESA-LOADER: failed to open crocus: /usr/lib/dri/crocus_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: crocus
libGL error: MESA-LOADER: failed to open crocus: /usr/lib/dri/crocus_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: crocus
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=pt_BR.UTF-8,Utf16=on,HugeFiles=on,64 bits,2 CPUs Intel(R) Celeron(R) CPU 1017U @ 1.60GHz (306A9),ASM)

Scanning the drive for archives:
1 file, 1604321280 bytes (1530 MiB)

Extracting archive: /home/lucaslds/Downloads/PrimeOS-2.1.0-64-bit-20220223-BETA.iso

WARNINGS:
There are data after the end of archive

--
Path = /home/lucaslds/Downloads/PrimeOS-2.1.0-64-bit-20220223-BETA.iso
Type = Iso
WARNINGS:
There are data after the end of archive
Physical Size = 1603536896
Tail Size = 784384
Created = 2022-02-23 11:20:22
Modified = 2022-02-23 11:20:22

Everything is Ok                   

Archives with Warnings: 1

Warnings: 1
Folders: 9
Files: 170
Size:       1607415197
Compressed: 1604321280
Traceback (most recent call last):
  File "installer.py", line 549, in Extracting
  File "genericpath.py", line 50, in getsize
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/ax86_35051691/ramdisk.img'
Aborted

**Comment by jaxparrow07** [comment]
Fixed in the latest release. Please, let me know if the problem persists.

**Comment by Gzushgshsh** [comment]
![image](https://user-images.githubusercontent.com/95548091/166918053-2369faaf-61ad-4a0f-820b-a2932bcfadcb.png)

Worked!

**Comment by Gzushgshsh** [comment]
![image](https://user-images.githubusercontent.com/95548091/166921738-de9503e4-365f-47ca-8d09-cb1cf77ea532.png)

It just had a problem creating an entry in GRUB but I don't think it's a problem with Androidx86-Installer-Linux

**Comment by jaxparrow07** [comment]
> ![image](https://user-images.githubusercontent.com/95548091/166921738-de9503e4-365f-47ca-8d09-cb1cf77ea532.png)
> 
> It just had a problem creating an entry in GRUB but I don't think it's a problem with Androidx86-Installer-Linux

Yea, it's a problem with Memtest entry.

**Comment by Gzushgshsh** [comment]
> 

Anyway, do you know any solution to this? I really do not know how to add an entry to the system?

**Comment by jaxparrow07** [comment]
> > 
> 
> Anyway, do you know any solution to this? I really do not know how to add an entry to the system?

Remove the memtest entries maybe. Goto `/etc/grub.d/` to see the grub entries.
