### ISSUE TITLE
Make /system an editable folder

### ISSUE THREAD

**Issue by Gzushgshsh** [jaxparrow07/Androidx86-Installer-Linux#9]
Is it possible to do that?

![](https://www.android-x86.org/screenshots/InstallSelectSystemRW.png)

**Comment by jaxparrow07** [comment]
> Is it possible to do that?
> 
> ![](https://www.android-x86.org/screenshots/InstallSelectSystemRW.png)
> 
> 

What you're suggesting to do is more like the supercharging feature present in ![gearlock](https://github.com/axonasif/gearlock)

And I don't personally think that should be in the installer since it may cause some issues ( in newer Android ). Try using gearlock for that.
